---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: DcimDevice
  data:
    # Amsterdam Site 01 — medium campus: 1 router, 1 dist switch, 2 access switches
    - name: AMS-RTR-01
      object_template: border-router
      location: ams-01
      member_of_groups:
        - campus_routers

    - name: AMS-DSW-01
      object_template: distribution-switch
      location: ams-01

    - name: AMS-ASW-01
      object_template: access-switch
      location: ams-01

    - name: AMS-ASW-02
      object_template: access-switch
      location: ams-01
