---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: LocationSite
  data:
    - name: London Site 01
      shortname: lon-01
      parent: london
      mgmt_prefix:
        - "172.16.1.0/24"
        - "default"

    - name: Amsterdam Site 01
      shortname: ams-01
      parent: amsterdam
      mgmt_prefix:
        - "172.16.2.0/24"
        - "default"

    - name: Munich Site 01
      shortname: muc-01
      parent: munich
      mgmt_prefix:
        - "172.16.3.0/24"
        - "default"
