---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: LocationSite
  data:
    - name: lon-01
      parent: London
      mgmt_prefix:
        - "default"
        - "172.16.1.0/24"

    - name: ams-01
      parent: Amsterdam
      mgmt_prefix:
        - "default"
        - "172.16.2.0/24"

    - name: muc-01
      parent: Munich
      mgmt_prefix:
        - "default"
        - "172.16.3.0/24"
