---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: LocationSite
  data:
    - name: London Site 01
      shortname: lon-01
      parent: london
      mgmt_pool: lon-mgmt-pool

    - name: Amsterdam Site 01
      shortname: ams-01
      parent: amsterdam
      mgmt_pool: ams-mgmt-pool

    - name: Munich Site 01
      shortname: muc-01
      parent: munich
      mgmt_pool: muc-mgmt-pool
