query AllDevices {
  DcimDevice(limit: 1000) {
    edges {
      node {
        id
        name {
          value
        }
        location {
          node {
            __typename
            shortname {
              value
            }
          }
        }
      }
    }
  }
}
