query CampusSite($shortname: String!) {
  LocationSite(shortname__value: $shortname) {
    edges {
      node {
        id
        shortname {
          value
        }
        mgmt_pool {
          node {
            id
          }
        }
        design {
          node {
            ... on OtnCampusSite {
              device_entries {
                edges {
                  node {
                    count {
                      value
                    }
                    template {
                      node {
                        id
                        ... on TemplateDcimDevice {
                          role {
                            value
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
