query CampusSite($shortname: String!) {
  LocationSite(shortname__value: $shortname) {
    edges {
      node {
        id
        shortname {
          value
        }
        design {
          node {
            ... on OtnCampusSite {
              bgp_asn {
                value
              }
              device_entries {
                edges {
                  node {
                    count {
                      value
                    }
                    template {
                      node {
                        id
                        role {
                          value
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
