query CampusSite($shortname: String!) {
  LocationSite(shortname__value: $shortname) {
    edges {
      node {
        id
        shortname {
          value
        }
        mgmt_prefix {
          node {
            id
          }
        }
        design {
          node {
            ... on OtnCampusSite {
              device_entries {
                edges {
                  node {
                    count {
                      value
                    }
                    device_hostname_prefix {
                      value
                    }
                    template {
                      node {
                        id
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
